version: '3.8'

services:
  # FastAPI Backend Service with Standalone High-Performance SQLite
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ivitsh_portal_backend
    restart: always
    environment:
      - DATABASE_URL=sqlite:///./portal.db
      - SECRET_KEY=ksu_ivitsh_production_jwt_super_secret_key_2026_secure
      - ALGORITHM=HS256
      - GIGACHAT_CLIENT_ID=019e2c26-97a8-75cf-8d25-1caf90fcdd51
      - GIGACHAT_SECRET=MDE5ZTJjMjYtOTdhOC03NWNmLThkMjUtMWNhZjkwZmNkZDUxOjFkODQ2YzZjLTgwNmEtNGIwZi1iZmQ2LTY0Zjg2NTAwMmU2Yg==
    volumes:
      - sqlite_data:/app/backend_data
    ports:
      - "8000:8000"

  # Nginx Web Server & Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ivitsh_portal_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  sqlite_data:
